### ISSUE TITLE
plugin works fine on 5.4 but not on 5.6.1

### ISSUE THREAD

**Issue by TRISAF** [nbs-system/mapster#11]
Hi,
this plugin works fine on 5.4 but not on 5.6.1

The error is:

```
Uncaught TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=15533:280)
Version: 5.6.1
Build: 15533
Error: Uncaught TypeError: __webpack_require__(...).register is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=15533:280)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15533:76:8884)
```

Any idea for fix this error?

Many thanks
Filippo

**Comment by purplesrl** [comment]
The problem is the last line in mapster.js:

require('ui/registry/vis_types').register(mapsterProvider);
